version: 2
jobs:
  install:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - ""
        
  unit_tests:
    docker:
      - image: circleci/node:12

    steps:
      - attach_workspace:
          at: .

      - run: yarn test
        
  prettier_check:
    docker:
      - image: circleci/node:12

    steps:
      - attach_workspace:
          at: .

      - run: yarn prettier-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - unit_tests: 
          requires:
              - install
      - prettier_check: 
          requires:
              - install